version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - 8080:80
    environment:
      ASPNET_CORE_ENVIRONMENT: Development
      ASPNETCORE_DATABASE_STRING: "Server=mysql;Database=lvlupcenter;User=lvlupcenter;Password=lvlupcenter"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.19
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lvlupcenter
      MYSQL_USER: lvlupcenter
      MYSQL_PASSWORD: lvlupcenter
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
